[workspace]
members = [
    "core",
    "config",
    "bridge/ffi",
]

default-members = [
    "core",
    "config",
    "bridge/ffi",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
strip = true
