[workspace]
members = [
    "core",
    "config",
    "ffi"
]

default-members = [
    "core",
    "config",
    "ffi"
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
strip = true
