[package]
name = "dsnp-graph-sdk-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false
exclude = ["graphsdk.node"]

[lib]
name = "graphsdk"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.0"
lazy_static = "1.4.0"
anyhow = "1.0.40"
neon = { version = "0.10.1", default-features = false, features = ["napi-6"] }
dsnp-graph-core = { version = "0.1.0", path = "../../core" }
dsnp-graph-config = { version = "0.1.0", path = "../../config" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
once_cell = "1.18.0"
