[package]
name = "dsnp-graph-sdk-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
name = "dsnp_graph_sdk_node"
crate-type = ["cdylib"]

[dependencies]
dsnp-graph-core = { version = "0.1.0", path = "../../core" }
dsnp-graph-config = { version = "0.1.0", path = "../../config" }
libc = "0.2.0"
lazy_static = "1.4.0"
anyhow = "1.0.40"
neon = "0.10.1"
