language = "C"
no_includes = true

[export]
item_types = [
    "functions",
]

[fn]
args = "horizontal"
sort_by = "Name"
rename_args = "camelCase"

[parse]
parse_deps = true
include = ["dsnp-graph-core", "dsnp-graph-config"]

[parse.expand]
crates = ["dsnp-graph-sdk-jni"]
