[package]
name = "dsnp-graph-core"
edition = "2021"
homepage = "https://spec.dsnp.org"
license = "Apache-2.0"
publish = false
repository = "https://github.com/libertyDSNP/graph-sdk/"
version = "0.0.0"

[dependencies]
wasm-bindgen = {version = "0.2.63", optional = true}
serde = { version = "1.0", features = ["derive"] }
apache-avro = { version = "0.14.0", features = ["snappy"] }
serde_bytes = "0.11.9"
lazy_static = "1.4.0"
thiserror = "1.0.39"
anyhow = "1.0.69"
miniz_oxide = "0.7.1"
dryoc = "0.4.3"
zeroize = "1.5.7"

[dev-dependencies]
pretty_assertions = "1.3.0"
rand = "0.8.5"

[features]
wasm = ["wasm-bindgen"]
