[package]
name = "graph-sdk-core"
edition = "2021"
homepage = "https://spec.dsnp.org"
license = "Apache-2.0"
publish = false
repository = "https://github.com/libertyDSNP/graph-sdk/"
version = "0.0.0"

[dependencies]
wasm-bindgen = {version = "0.2.63", optional = true}
serde = { version = "1.0", features = ["derive"] }
apache-avro = { version = "0.14.0", features = ["snappy"] }
serde_bytes = "0.11.9"
lazy_static = "1.4.0"
thiserror = "1.0.39"
anyhow = "1.0.69"
miniz_oxide = "0.7.1"
crypto_box = { version = "0.8.2", features = ["seal"] }

[dev-dependencies]
rand = "0.8.5"

[features]
wasm = ["wasm-bindgen"]
