name: Verify PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-rust-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build and test
      run: |
        cargo build --verbose
        cargo test --verbose
