name: Verify PR Commit
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  verify:
    name: Check PR Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Cargo check
        run: make check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Cargo test
        run: make test

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Cargo fmt
        run: make format-check

  #  clippy:
  #    name: Run clippy
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v3
  #        with:
  #          fetch-depth: 0
  #
  #      - name: Install Rust Toolchain
  #        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
  #        with:
  #          toolchain: stable
  #          default: true
  #          profile: minimal
  #          target: wasm32-unknown-unknown
  #
  #      - name: Cargo clippy
  #        run: make clippy

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Cargo build
        run: make build
  test_binary:
    name: Generate bindgen and run c_example
    runs-on: ubuntu-latest
    needs: [verify, test, lint, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Install libsodium
        run: sudo apt-get install -y libsodium-dev
      - name: Run tests for ffi
        run: make test-ffi
      - name: Upload artifacts dsnp_graph_sdk_ffi.h and libdsnp_graph_sdk_ffi.a
        uses: actions/upload-artifact@v2
        with:
          name: dsnp_graph_sdk_ffi
          path: |
            bridge/ffi/src/c_example/dsnp_graph_sdk_ffi.h
            bridge/ffi/src/c_example/libdsnp_graph_sdk_ffi.a
            bridge/ffi/src/c_example/main.c

  generate-docs:
    name: Generate graph sdk rust docs
    runs-on: ubuntu-latest
    needs: [verify, test, lint, build, test_binary]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Build Rust Docs
        run: RUSTDOCFLAGS="--enable-index-page --check -Zunstable-options" cargo doc --no-deps --all-features
  
  build_gradlew_jvm:
    name: Build jvm
    runs-on: ubuntu-latest
    needs: [verify, test, lint, build, test_binary]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build JNI package
        run: make build-jni
      - name: Build with Gradle
        run:  cd java && ./gradlew build
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBERTY_READ_TOKEN: ${{ secrets.LIBERTY_READ_TOKEN }}
          LIBERTY_READ_ACTOR: ${{ secrets.LIBERTY_READ_ACTOR }}